const exercises = [
  // QUADRICEPS
  {
    name: 'Leg press',
    muscleGroup: 'thigh',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Squat',
    muscleGroup: 'thigh',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,

  },
  {
    name: 'Seated knee extension',
    muscleGroup: 'thigh',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  // HAMSTRING
  {
    name: 'Deadlift',
    muscleGroup: 'hamstring',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Leg curls',
    muscleGroup: 'hamstring',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  // CALVES
  {
    name: 'Standing calf raise',
    muscleGroup: 'calf',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,

  },
  {
    name: 'Seated calf raise',
    muscleGroup: 'calf',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  // CHEST
  {
    name: 'Bench press',
    muscleGroup: 'chest',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Dips',
    muscleGroup: 'chest',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  // BACK
  {
    name: 'Machine rows',
    muscleGroup: 'back',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Pull up machine',
    muscleGroup: 'back',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  //SHOULDERS
  {
    name: 'Lateral raise',
    muscleGroup: 'shoulders',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Shrugs',
    muscleGroup: 'shoulders',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  //CORE
  {
    name: 'Leg lifts',
    muscleGroup: 'core',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Crunches',
    muscleGroup: 'core',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Cable twists',
    muscleGroup: 'core',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  //BICEPS
  {
    name: 'Bicep curls',
    muscleGroup: 'biceps',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Concentration curls',
    muscleGroup: 'biceps',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  //TRICEPS
  {
    name: 'Cable pulldown',
    muscleGroup: 'triceps',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
  {
    name: 'Tricep overhead extension',
    muscleGroup: 'triceps',
    chosen: false,
    weight: 0,
    reps: 0,
    firstSet: 0,
    secondSet: 0,
    thirdSet: 0,
    availability: 0,
    goal: '',
    isOpen: false,
  },
];

export default exercises